exitOnIssue flag
GertjanReynaert/react-intl-translations-manager pull request #97
Opened 2017-05-24 21:59 UTC by tay1orjones

Should resolve #88 and enable the CLI to exit with code `1` for CI build tools, etc

Includes documentation/usage updates

Let me know what you think @GertjanReynaert  🙂

2017-05-29 22:25 UTC, bf commented
Please merge this, the package becomes very useful now.

2017-11-09 22:34 UTC, ctumolosus commented
@GertjanReynaert do you have some time to review this PR? Would love to see this feature released.

2018-03-29 19:40 UTC, GertjanReynaert requested changes
Hey @tay1orjones, first of all, apologies for the late response.

Are you still up to finishing this pr? If not, no problem, just let me know.

Apart from the rebase that needs to happen, I have a few remarks that are written down in the review I did.

2018-03-29 19:40 UTC, GertjanReynaert commented on README.md
> +- `exitOnIssue` (optional, default: `true`)
Can you change this default to `false` since that's the default you used [here](https://github.com/GertjanReynaert/react-intl-translations-manager/pull/97/files#diff-1e35bc10b1bfd304a61e72973918ee56R31)

2018-03-29 19:40 UTC, GertjanReynaert commented on src/manageTranslations.js
> +        exitOnIssue ? process.exitCode = 1 : null;
Can you move this line to the line after [this line](https://github.com/tay1orjones/react-intl-translations-manager/blob/f70f3256e5d21b8c8edd8f1c810c5285b0652e6a/src/manageTranslations.js#L100) in the `outputDuplicateKeys` core method? Since the printer methods should only be concerned about printing to the console, it doesn't really fit here.

2018-03-29 19:40 UTC, GertjanReynaert commented on src/manageTranslations.js
> +      printResults({ ...langResults.report, sortKeys, exitOnIssue });
Can you move this exitOnIssue implementation to [this line](https://github.com/tay1orjones/react-intl-translations-manager/blob/f70f3256e5d21b8c8edd8f1c810c5285b0652e6a/src/manageTranslations.js#L145) in the `reportLanguage` core method? Same reason as the previous comment.

2019-01-29 06:44 UTC, amakhrov commented
Any plans to move forward with that?

2019-08-19 11:45 UTC, pierreferry commented
What are the blocking points for the PR atm ? That would be a great feature for me !

2022-08-30 19:05 UTC, closed without merging